export const raretryrunVariables = {
  rtrRewardPerRare: {
    whiteDove: 125,
    stinkyPig: 3500,
    pinkyPig: 125,
    goldenPheasant: 250,
    marshDeer: 1250,
    doe: 0,
    muskDeer: 4000,
    jackass: 1000,
    rareMacaw: 40000,
    blueMacaw: 0,
    girabie: 1500,
    momaffieFamily: 250,
    momaffie: 125,
    rareToucan: 40000,
    lavaToucan: 3500,
    fieryToucan: 0,
    keelBilledToucan: 0,
    chocoToucan: 0,
    blackPanther: 750,
    leopard: 0,
    jaguar: 0,
    demonPufferfish: 3000,
    yellowPufferfish: 0,
    blackTiger: 3500,
    whiteTiger: 200,
    blackBear: 300,
    blackLion: 15000,
    whiteLion: 3000,
    blackManedLion: 1000,
    blackLioness: 15000,
    whiteLioness: 3000,
    lioness: 0,
    blackLionCub: 15000,
    whiteLionCub: 3000,
    lionCub: 200,
    shaheen: 55000,
    predator: 1000,
    rareVulture: 40000,
    bigGoat: 666,
    markhor: 0,
    blackRhino: 7000,
    whiteRhino: 3500,
    greaterSpottedEagle: 75000,
    harpyEagle: 75000,
    goldenEagle: 2000,
    giraffeFamily: 2500,
    whiteGiraffe: 500,
    aquaYeti: 300,
    shopBigfoot: 125,
    shopSnowman: 125,
    shopSnowgirl: 125,
    rareBigfoot: 15000,
    rareSnowman: 15000,
    rareSnowgirl: 30000,
    rareKingDragon: 15000
  },

  rtrLuckKey: [
    ["pigeon", "whiteDove"], 
    ["pig", "pinkyPig", "stinkyPig"],
    ["deer", "doe", "marshDeer"],
    ["reindeer", "muskDeer"],
    ["swinehoe", "goldenPheasant"],
    ["donkey", "jackass"],
    ["macaw", "blueMacaw", "rareMacaw"],
    ["giraffe", "momaffie", "momaffieFamily", "girabie"],
    ["cheetah", "jaguar", "leopard", "blackPanther"],
    ["toucan", "chocoToucan", "keelBilledToucan", "fieryToucan", "lavaToucan", "rareToucan"],
    ["pufferfish", "yellowPufferfish", "demonPufferfish"],
    ["tiger", "whiteTiger"],
    ["lion", "lioness", "lionCub", "blackManedLion", "whiteLionCub", "whiteLioness", "whiteLion", "blackLionCub", "blackLioness", "blackLion"],
    ["falcon", "predator", "shaheen"],
    ["vulture", "rareVulture"],
    ["rhino", "whiteRhino", "blackRhino"],
    ["baldEagle", "goldenEagle", "harpyEagle", "greaterSpottedEagle"],
    [null, "markhor", "bigGoat"],
    [null, "whiteGiraffe", "giraffeFamily"],
    ["yeti", "aquaYeti"],
    [null, "rareBigfoot", "shopBigfoot"],
    [null, "rareSnowman", "shopSnowman"],
    [null, "rareSnowgirl", "shopSnowgirl"],
    ["blackDragon", "rareKingDragon"]
  ]
}